### ISSUE TITLE
可以提供一下论文pdf吗？

### ISSUE THREAD

**Issue by ShelveyJ** [Skyyyy0920/MTNet#3]
作者您好，可以麻烦提供一份论文呢的pdf吗？

**Comment by ckq11903** [comment]
> 作者您好，可以麻烦提供一份论文呢的pdf吗？

方便联系你讨论交流下吗？

**Comment by Skyyyy0920** [comment]
[Uploading Learning Time Slot Preferences via Mobility Tree for Next POI Recommendation.pdf…]()
