### ISSUE TITLE
I am very interested in your research. Can you provide the other two datasets.

### ISSUE THREAD

**Issue by Zs1235** [Skyyyy0920/MTNet#4]

**Comment by Skyyyy0920** [comment]
Thank you for your interest in our research, here is the other two datasets: [other_datasets.zip](https://github.com/Skyyyy0920/MTNet/files/14740025/other_datasets.zip)

**Comment by renrui70** [comment]
> Thank you for your interest in our research, here is the other two datasets: [other_datasets.zip](https://github.com/Skyyyy0920/MTNet/files/14740025/other_datasets.zip)

The download data failed and authorization is required, can you authorize it? Thank you so much!

**Comment by Skyyyy0920** [comment]
> > Thank you for your interest in our research, here is the other two datasets: [other_datasets.zip](https://github.com/Skyyyy0920/MTNet/files/14740025/other_datasets.zip)
> 
> The download data failed and authorization is required, can you authorize it? Thank you so much!

The link is still available, maybe you need VPN to download it.

**Comment by renrui70** [comment]
> > Thank you for your interest in our research, here is the other two datasets: [other_datasets.zip](https://github.com/Skyyyy0920/MTNet/files/14740025/other_datasets.zip)
> 
> The download data failed and authorization is required, can you authorize it? Thank you so much!



> > > Thank you for your interest in our research, here is the other two datasets: [other_datasets.zip](https://github.com/Skyyyy0920/MTNet/files/14740025/other_datasets.zip)
> > 
> > 
> > The download data failed and authorization is required, can you authorize it? Thank you so much!
> 
> The link is still available, maybe you need VPN to download it.

I download it successfully.Thanks!

> > > Thank you for your interest in our research, here is the other two datasets: [other_datasets.zip](https://github.com/Skyyyy0920/MTNet/files/14740025/other_datasets.zip)
> > 
> > 
> > The download data failed and authorization is required, can you authorize it? Thank you so much!
> 
> The link is still available, maybe you need VPN to download it.

I download it successfully.Thanks!

**Comment by renrui70** [comment]
> > > Thank you for your interest in our research, here is the other two datasets: [other_datasets.zip](https://github.com/Skyyyy0920/MTNet/files/14740025/other_datasets.zip)
> > 
> > 
> > The download data failed and authorization is required, can you authorize it? Thank you so much!
> 
> The link is still available, maybe you need VPN to download it.

I download it successfully.Thanks!
