### ISSUE TITLE
数据预处理

### ISSUE THREAD

**Issue by Mediocre250** [Skyyyy0920/MTNet#5]
求一份大佬的数据预处理代码
按照文章中陈述的预处理步骤：
1.数据清洗
2.通过用户、时间划分轨迹
3.通过时间划分训练集、验证集、测试集

处理后的数据会导致训练集中POI并没有包含所有的POI，即测试集中会出现新POI，而代码中似乎没有对此做一些特殊处理。
我尝试用自己的数据集处理后运行代码，但是因为这个问题，训练过程没有问题，但测试中报了KeyError
救救孩子吧

**Comment by Skyyyy0920** [comment]
仓库中给出的数据已经是预处理过之后的数据了，不需要再进行额外的处理，也不会出现你所说的这种问题。如果想使用自己的数据集，请参考[GetNext](https://dl.acm.org/doi/abs/10.1145/3477495.3531983?casa_token=W-lrH91Sv3QAAAAA:Wy8cPbg8vI-bZKwbd-8Qag9guvlUkMI1H0kIRW9AGsBghlgyXLW4MAcg2pH84eexar1-NMjgawcjyQ)，但是据我所知他们也并没有开源预处理数据的代码。
