### ISSUE TITLE
Can you provide the data preprocessing code？

### ISSUE THREAD

**Issue by ForAxel** [Skyyyy0920/MTNet#6]
This repo is an incredibly intriguing work and I am eager to replicate your experimental results starting from the raw check-in data. I would appreciate more details on how you preprocess those raw check-in data. If you can share the data preprocessing code, that would be immensely helpful.

**Comment by Skyyyy0920** [comment]
Thank you for your interest in our work. The data provided in the repository has already been preprocessed, so no additional processing is required. If you want to use your own dataset, please refer to [GetNext](https://dl.acm.org/doi/abs/10.1145/3477495.3531983?casa_token=W-lrH91Sv3QAAAAA:Wy8cPbg8vI-bZKwbd-8Qag9guvlUkMI1H0kIRW9AGsBghlgyXLW4MAcg2pH84eexar1-NMjgawcjyQ), as we follow their preprocessing method. However, as far as I know, they have not open-sourced the code for preprocessing the data.
